STANDARD_TYPES = (
    "ID",
    "Boolean",
    "Float",
    "Int",
    "String",
    "__Schema",
    "__Type",
    "__TypeKind",
    "__Field",
    "__InputValue",
    "__EnumValue",
    "__Directive",
    "__DirectiveLocation",
)
